### ISSUE TITLE
Fails when the specified source is a subdir of jsons

### ISSUE THREAD

**Issue by etoiledemer** [fadhilx/json_to_model#25]
`flutter pub run json_to_model --source="./jsons/some_dir"`

```
RangeError (startIndex): Invalid value: Not in inclusive range 0..48: 57
#0      RangeError.checkValueInInterval (dart:core/errors.dart:282:7)
#1      _StringBase.replaceFirst (dart:core-patch/string_patch.dart:586:16
```

**Comment by mark-nicepants** [comment]
Hey @etoiledemer. Is this related to the other subdirs issues? Or does this still throw an error after upgrading to version 3.0.2
