### ISSUE TITLE
sensitive to "*list*" key

### ISSUE THREAD

**Issue by etoiledemer** [fadhilx/json_to_model#33]
When the word `list` appears in a key, an exception occurs
```
{
  "a": {
    "listed": {
      "c": 1
    }
  }
}
```

```
Unhandled exception:
Cannot determine faker for type ``
#0      FakerMaker.generate (package:json_to_model/utils/faker_maker.dart:39:5)
#1      DartDeclaration.toMockDeclaration.<anonymous closure> (package:json_to_model/core/dart_declaration.dart:40:43)
#2      DartDeclaration.checkNestedTypes (package:json_to_model/core/dart_declaration.dart:180:20)
#3      DartDeclaration.toMockDeclaration (package:json_to_model/core/dart_declaration.dart:38:19)
#4      JsonKeyModels.toMockDeclarationStrings.<anonymous closure> (package:json_to_model/utils/extensions.dart:85:67)
#5      MappedIterator.moveNext (dart:_internal/iterable.dart:391:20)
#6      Iterable.join (dart:core/iterable.dart:356:19)
#7      JsonKeyModels.toMockDeclarationStrings (package:json_to_model/utils/extensions.dart:85:97)
#8      new JsonModel (package:json_to_model/core/json_model.dart:43:40)
#9      new JsonModel.fromMap (package:json_to_model/core/json_model.dart:74:12)
#10     defaultCommandCallback (package:json_to_model/core/command.dart:43:38)
#11     new DartDeclaration.fromCommand (package:json_to_model/core/dart_declaration.dart:308:35)
#12     new DartDeclaration.fromKeyValue (package:json_to_model/core/dart_declaration.dart:268:39)
#13     new JsonModel.fromMap.<anonymous closure> (package:json_to_model/core/json_model.dart:70:51)
#14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
#15     new JsonModel.fromMap (package:json_to_model/core/json_model.dart:69:13)
#16     JsonModelRunner._iterateOverJsonFiles.<anonymous closure> (package:json_to_model/index.dart:57:39)
#17     List.forEach (dart:core-patch/growable_array.dart:403:8)
#18     JsonModelRunner._iterateOverJsonFiles (package:json_to_model/index.dart:38:50)

```

if I change the `listed` key for `liXted`, all is good:
```
{
  "a": {
    "liXted": {
      "c": 1
    }
  }
}
```

**Comment by mark-nicepants** [comment]
Nice find, fixed in 3.1.7 ill publish this version asap
