### ISSUE TITLE
Improve error message when type cannot be inferred (Cannot determine faker for type `dynamic`)

### ISSUE THREAD

**Issue by mitchross** [fadhilx/json_to_model#36]
New Bug extention of https://github.com/fadhilx/json_to_model/issues/34 on 3.1.6

Unhandled exception:
Cannot determine faker for type `dynamic`
#0      FakerMaker.generate (package:json_to_model/utils/faker_maker.dart:39:5)
#1      DartDeclaration.toMockDeclaration.<anonymous closure> (package:json_to_model/core/dart_declaration.dart:39:43)
#2      DartDeclaration.checkNestedTypes (package:json_to_model/core/dart_declaration.dart:181:20)
#3      DartDeclaration.toMockDeclaration (package:json_to_model/core/dart_declaration.dart:37:19)
#4      JsonKeyModels.toMockDeclarationStrings.<anonymous closure> (package:json_to_model/utils/extensions.dart:85:67)
#5      MappedIterator.moveNext (dart:_internal/iterable.dart:391:20)
#6      Iterable.join (dart:core/iterable.dart:431:23)
#7      JsonKeyModels.toMockDeclarationStrings (package:json_to_model/utils/extensions.dart:85:97)
#8      new JsonModel (package:json_to_model/core/json_model.dart:42:40)
#9      new JsonModel.fromMap (package:json_to_model/core/json_model.dart:73:12)

```JSON
{
    "adult": false,
    "backdrop_path": "/12NEw3eBUQxK9qdgtegZRsz4Yp8.jpg",
    "created_by": [
        {
            "id": 15344,
            "credit_id": "525775af760ee36aaa51895a",
            "name": "J.J. Abrams",
            "gender": 2,
            "profile_path": "/uiEVOx3QclxnN76t8PU6v5IcUUP.jpg"
        },
        {
            "id": 28974,
            "credit_id": "525775af760ee36aaa518960",
            "name": "Damon Lindelof",
            "gender": 2,
            "profile_path": "/pDOGmg9wlE6OBa4UHPjOgNrLugT.jpg"
        },
        {
            "id": 1237491,
            "credit_id": "525775af760ee36aaa518954",
            "name": "Jeffrey Lieber",
            "gender": 2,
            "profile_path": null
        }
    ],
    "episode_run_time": [
        45,
        42
    ],
    "first_air_date": "2004-09-22",
    "genres": [
        {
            "id": 10759,
            "name": "Action & Adventure"
        },
        {
            "id": 9648,
            "name": "Mystery"
        }
    ],
    "homepage": "http://abc.go.com/shows/lost",
    "id": 4607,
    "in_production": false,
    "languages": [
        "en"
    ],
    "last_air_date": "2010-05-23",
    "last_episode_to_air": {
        "air_date": "2010-05-23",
        "episode_number": 18,
        "id": 334043,
        "name": "The End (2)",
        "overview": "For different reasons, Jack and the Man in Black both use Desmond to extinguish the light at the heart of the island. The island starts disintegrating, but The Man in Black is also made mortal. Still desperate to escape, The Man in Black fights Jack and mortally wounds him, but with help from Kate, Jack kills him. Realizing his destiny, Jack sacrifices himself to relight the heart of the island, so his friends can escape on the Ajira plane. Hurley takes Jack's place as protector of the island and makes Ben the new advisor. The flash sideways is revealed to be a type of limbo, or holding pattern, for the main characters, where they reside until accepting their life and death, and are then able to \"let go\" and \"move on\" together.",
        "production_code": "618",
        "season_number": 6,
        "still_path": "/cW1GejJtT6CSNeFwaOzd824E8pt.jpg",
        "vote_average": 8.4,
        "vote_count": 10
    },
    "name": "Lost",
    "next_episode_to_air": null,
    "networks": [
        {
            "name": "ABC",
            "id": 2,
            "logo_path": "/2uy2ZWcplrSObIyt4x0Y9rkG6qO.png",
            "origin_country": "US"
        }
    ],
    "number_of_episodes": 120,
    "number_of_seasons": 6,
    "origin_country": [
        "US"
    ],
    "original_language": "en",
    "original_name": "Lost",
    "overview": "Stripped of everything, the survivors of a horrific plane crash  must work together to stay alive. But the island holds many secrets.",
    "popularity": 161.042,
    "poster_path": "/og6S0aTZU6YUJAbqxeKjCa3kY1E.jpg",
    "production_companies": [
        {
            "id": 19366,
            "logo_path": "/vOH8dyQhLK01pg5fYkgiS31jlFm.png",
            "name": "ABC Studios",
            "origin_country": "US"
        },
        {
            "id": 11461,
            "logo_path": "/p9FoEt5shEKRWRKVIlvFaEmRnun.png",
            "name": "Bad Robot",
            "origin_country": "US"
        }
    ],
    "production_countries": [
        {
            "iso_3166_1": "US",
            "name": "United States of America"
        }
    ],
    "seasons": [
        {
            "air_date": "2005-04-27",
            "episode_count": 33,
            "id": 14047,
            "name": "Specials",
            "overview": "",
            "poster_path": "/u1hvfXTqebq6Na5zhzHiJYZT0YK.jpg",
            "season_number": 0
        },
        {
            "air_date": "2004-09-22",
            "episode_count": 24,
            "id": 14041,
            "name": "Season 1",
            "overview": "Mysteries abound on the first season of LOST as the survivors of Oceanic Air flight 815 find themselves stranded on an unidentified island with little hope of rescue.",
            "poster_path": "/fc9f4ERC09U1GziCgDWilWWgjKx.jpg",
            "season_number": 1
        },
        {
            "air_date": "2005-09-21",
            "episode_count": 24,
            "id": 14042,
            "name": "Season 2",
            "overview": "The second season of the American serial drama television series Lost commenced airing in the United States and Canada on September 21, 2005 and concluded on May 24, 2006. The second season continues the stories of a group of over forty people who have been stranded on a remote island in the south Pacific, after their airplane crashed forty-four days prior to the beginning of the season. The producers have stated that as the first season is about introducing the survivors, the second season is about a 1970s scientific Dharma Initiative research station which the survivors discovered on the island and refer to as \"the hatch\". The second season aired Wednesdays at 9:00 pm in the United States. In addition to the regular twenty-four episodes, three clip-shows recapped previous events on the show. \"Destination Lost\" aired before the premiere, \"Lost: Revelation\" aired before the tenth episode and \"Lost: Reckoning\" aired before the twentieth episode. The season was released on DVD as a seven disc boxed set under the title of Lost: The Complete Second Season – The Extended Experience on September 5, 2006 by Buena Vista Home Entertainment.",
            "poster_path": "/vGLddXoXJhKPsAWeDYbAsE4wW1z.jpg",
            "season_number": 2
        },
        {
            "air_date": "2006-10-04",
            "episode_count": 23,
            "id": 14043,
            "name": "Season 3",
            "overview": "The third season of the American serial drama television series Lost commenced airing in the United States and Canada on October 4, 2006 and concluded on May 23, 2007. The third season continues the stories of a group of over 40 people who have been stranded on a remote island in the South Pacific, after their airplane crashed 68 days prior to the beginning of the season. In the Lost universe, the season takes place from November 28 to December 21, 2004. The producers have stated that as the first season is about introducing the survivors and the second season is about the hatch, the third season is about the Others, a group of mysterious island inhabitants.\n\nIn response to fan complaints about scheduling in the previous seasons, ABC decided to air the episodes without reruns, albeit in two separate blocks. In the United States, the first block consisted of six episodes aired on Wednesdays at 9:00 pm and after a twelve week break, the season continued with the remaining 16 episodes at 10:00 pm. In addition, three clip-shows recapped previous events on the show. \"Lost: A Tale of Survival\" aired a week before the season premiere, \"Lost Survivor Guide\" aired before the seventh episode and \"Lost: The Answers\" aired before the season finale Buena Vista Home Entertainment released the season under the title Lost: The Complete Third Season – The Unexplored Experience on December 11, 2007 in Region 1 on DVD and Blu-ray Disc.",
            "poster_path": "/zLnuh6DVyrz5iaNVO6KNKubtffo.jpg",
            "season_number": 3,
            "networks": [
                {
                    "id": 2,
                    "logo": {
                        "path": "/2uy2ZWcplrSObIyt4x0Y9rkG6qO.png",
                        "aspect_ratio": 1.0
                    },
                    "name": "ABC",
                    "origin_country": "US"
                }
            ]
        },
        {
            "air_date": "2008-01-31",
            "episode_count": 14,
            "id": 14044,
            "name": "Season 4",
            "overview": "The fourth season of the American serial drama television series Lost commenced airing on the American Broadcasting Company Network in the United States, and on CTV in Canada on January 31, 2008 and concluded on May 29, 2008. The season continues the stories of a group of over 40 people who have been stranded on a remote island in the South Pacific, after their airplane crashed there more than 90 days prior to the beginning of the season. According to Lost's executive producers/writers/showrunners Damon Lindelof and Carlton Cuse, there are two main themes in fourth season: \"the castaways' relationship to the freighter folk\" and \"who gets off the island and the fact that they need to get back\". Lost came under scrutiny from critics in its third season, but the fourth season was acclaimed for its flash-forwards, pace and new characters.\n\nThe season was originally planned to contain 16 episodes; eight were filmed before the start of the 2007–2008 Writers Guild of America strike. Following the strike's resolution, it was announced that only five more episodes would be produced to complete the season; however, the season finale's script was so long that network executives approved the production of a 14th episode as part of a three-hour season finale split over two nights. The fourth season aired Tuesdays at 9:00 pm from January 31 to March 20, 2008 and at 10:00 pm from April 24 to May 15, 2008. The two-hour finale aired at 9:00 pm on May 29, 2008. Buena Vista Home Entertainment released the season on DVD and Blu-ray Disc under the title Lost: The Complete Fourth Season – The Expanded Experience on December 9, 2008 in Region 1; however, it was released earlier—on October 20, 2008—in Region 2.",
            "poster_path": "/TOfSxtW76sWrPn3YSm5GooaR3Y.jpg",
            "season_number": 4,
            "networks": [
                {
                    "id": 2,
                    "logo": {
                        "path": "/2uy2ZWcplrSObIyt4x0Y9rkG6qO.png",
                        "aspect_ratio": 1.0
                    },
                    "name": "ABC",
                    "origin_country": "US"
                }
            ]
        },
        {
            "air_date": "2009-01-21",
            "episode_count": 17,
            "id": 14045,
            "name": "Season 5",
            "overview": "The fifth season of the American serial drama television series Lost commenced airing on the ABC network in the United States and on A in Canada in January 2009, and concluded with a two-hour season finale on May 13, 2009. The season continues the stories of the survivors of the fictional crash of Oceanic Airlines Flight 815, after some of them are rescued and those still stranded seemingly disappear to an unknown location and time with the island that they inhabit.\n\nAccording to Lost's co-creator/executive producer/writer/show runner Damon Lindelof, the season \"is about why [the people who have left the island] need to get back\". Lost returned on January 21, 2009 on ABC with a three-hour premiere consisting of a clip-show and two back-to-back new episodes. The remainder of the season aired on Wednesdays at 9:00 pm EST. The season began in the UK and Ireland on January 25, 2009 on Sky1 and RTÉ Two, respectively. The season was released on DVD and Blu-ray Disc under the title Lost: The Complete Fifth Season – The Journey Back, Expanded Edition on December 8, 2009.",
            "poster_path": "/2OYKA6UIC56loPxgL4IMshg4mVr.jpg",
            "season_number": 5
        },
        {
            "air_date": "2010-02-02",
            "episode_count": 18,
            "id": 14046,
            "name": "Season 6",
            "overview": "After Season 5’s explosive finish, everything is up in the air for the survivors of flight 815. No one knows what — or who — the future will hold. Will Juliet’s sacrifice to save her friends work? Can Kate choose, once and for all, between Jack and Sawyer? Will Sun and Jin be reunited? Is it too late to save Claire? Whatever awaits everyone on the island, one thing is for certain — the moment of truth has arrived.",
            "poster_path": "/xUb57GiEwg6pJpU4F3e01PKRVlc.jpg",
            "season_number": 6
        }
    ],
    "spoken_languages": [
        {
            "english_name": "English",
            "iso_639_1": "en",
            "name": "English"
        }
    ],
    "status": "Ended",
    "tagline": "Everything happens for a reason.",
    "type": "Scripted",
    "vote_average": 7.9,
    "vote_count": 2795
}
```

**Comment by mark-nicepants** [comment]
Thanks for providing an example json, ill look into it!

**Comment by mark-nicepants** [comment]
the `next_episode_to_air` value in the json is `null`, hence the dynamic because json2model cannot infer the type. If you add some content there it should work. Ill work on a better error message for a future version.

**Comment by mark-nicepants** [comment]
New (more elaborate) error is added in version 3.1.8 (available on pub.dev now)
